/**
 * B2's back-end ecosystems — Java (Maven/Gradle), Go, .NET (NuGet) and Rust
 * (Cargo) — end to end against the real stack: real Postgres, real API server,
 * real row-level security. No `page.route` appears in this file.
 *
 * Until this landed the dependency collector read npm and PyPI only, which
 * excludes most enterprise back ends: a bank submitting its whole monorepo got
 * a `dependency` surface marked *examined* on the strength of a
 * `package-lock.json` belonging to its front end. The point of the assertions
 * below is not that a parser works — `lib/collectors` unit-tests that over
 * fixtures — but that a submission of one of these files actually reaches the
 * **inventory**, which is the only place a CISO sees it.
 *
 * What would fail if this regressed, in order of how quietly it would land:
 *
 *  1. a file parsing fine and producing an asset nobody can read back, because
 *    `location`'s purl shape does not round-trip through the ingest;
 *  2. `ecosystems` in the response drifting from what was actually read, which
 *    is the scope `assetsMarkedGone` reconciles against — get it wrong and a
 *    Go submission marks a project's Maven assets `gone`;
 *  3. a version this collector cannot know (BOM-managed, or an MSBuild
 *    property) coming back as the placeholder text instead of null.
 *
 * The request count is kept deliberately low: the suite as a whole already
 * sits close to the S6/S7 rate-limit budget (see CLAUDE.md), and a chatty spec
 * here 429s the ones after it rather than itself.
 */
import { test, expect } from "./support/fixtures";

type APIRequestContext = import("@playwright/test").APIRequestContext;

interface DependencyIngestSummary {
  projectId: number;
  lockfilesRecognised: number;
  lockfiles: Array<{ path: string; kind: string }>;
  ecosystems: string[];
  collectionRunId: number | null;
  assetsCreated: number;
  assetsUpdated: number;
  observationsCreated: number;
  assetsMarkedGone: number;
  evidenceCaveat: string;
}

interface InventoryAsset {
  id: number;
  surface: string;
  algorithm: string;
  keySize: number | null;
  location: string;
  status: string;
  latestConfidence: number | null;
}

interface InventoryAssets {
  assets: InventoryAsset[];
}

/** A real `gradle.lockfile`, cut down. Bouncy Castle plus a non-crypto library that must produce nothing. */
const GRADLE_LOCKFILE = [
  "# This is a Gradle generated file for dependency locking.",
  "# Manual edits can break the build and are not advised.",
  "net.i2p.crypto:eddsa:0.3.0=compileClasspath,runtimeClasspath",
  "org.bouncycastle:bcprov-jdk18on:1.78.1=compileClasspath,runtimeClasspath",
  "org.slf4j:slf4j-api:2.0.13=compileClasspath,runtimeClasspath",
  "empty=annotationProcessor,testAnnotationProcessor",
  "",
].join("\n");

/** A `go.mod` with the `!`-escape-free spelling and a major-version suffix in the path. */
const GO_MOD = [
  "module github.com/acme/ledger",
  "",
  "go 1.22",
  "",
  "require (",
  "\tgithub.com/btcsuite/btcd/btcec/v2 v2.3.4",
  "\tgithub.com/cloudflare/circl v1.3.9",
  "\tgithub.com/spf13/cobra v1.8.1",
  ")",
  "",
].join("\n");

/** A `.csproj` under central package management: the reference carries no version at all. */
const CSPROJ = [
  '<Project Sdk="Microsoft.NET.Sdk">',
  "  <ItemGroup>",
  '    <PackageReference Include="BouncyCastle.Cryptography" />',
  '    <PackageReference Include="Serilog" Version="4.0.0" />',
  "  </ItemGroup>",
  "</Project>",
  "",
].join("\n");

/** A `Cargo.lock`, which is exact in a way none of the three above are. */
const CARGO_LOCK = [
  "# This file is automatically @generated by Cargo.",
  "version = 3",
  "",
  "[[package]]",
  'name = "rsa"',
  'version = "0.9.6"',
  'source = "registry+https://github.com/rust-lang/crates.io-index"',
  "",
  "[[package]]",
  'name = "serde"',
  'version = "1.0.204"',
  "",
].join("\n");

async function createProject(api: APIRequestContext, name: string): Promise<number> {
  const res = await api.post("/api/projects", { data: { name, language: "python", code: "" } });
  expect(res.status()).toBe(201);
  return ((await res.json()) as { id: number }).id;
}

async function submit(
  api: APIRequestContext,
  projectId: number,
  files: Array<{ path: string; content: string }>,
): Promise<DependencyIngestSummary> {
  const res = await api.post(`/api/projects/${projectId}/dependencies`, { data: { files } });
  expect(res.status()).toBe(200);
  return (await res.json()) as DependencyIngestSummary;
}

test.describe("the dependency collector's back-end ecosystems (B2)", () => {
  test("a polyglot repository's Java, Go, .NET and Rust dependencies all reach the inventory", async ({ api }) => {
    const projectId = await createProject(api, "B2 polyglot back end");

    const ingested = await submit(api, projectId, [
      { path: "services/signing/gradle.lockfile", content: GRADLE_LOCKFILE },
      { path: "services/ledger/go.mod", content: GO_MOD },
      { path: "src/Portal/Portal.csproj", content: CSPROJ },
      { path: "crates/vault/Cargo.lock", content: CARGO_LOCK },
      // Submitted alongside and ignored rather than rejected, which is what
      // lets a caller send a whole tree.
      { path: "README.md", content: "# ledger" },
    ]);

    expect(ingested.lockfilesRecognised).toBe(4);
    expect(ingested.lockfiles.map((l) => l.kind).sort()).toEqual(["cargo-lock", "dotnet-project", "go-mod", "gradle-lock"]);
    // The new response field. This is the exact set `assetsMarkedGone` was
    // scoped to, so it is a claim about what this run may say anything about.
    expect([...ingested.ecosystems].sort()).toEqual(["cargo", "golang", "maven", "nuget"]);
    expect(ingested.collectionRunId).not.toBeNull();
    expect(ingested.assetsCreated).toBeGreaterThan(0);
    expect(ingested.evidenceCaveat).toMatch(/resolved dependency graph/i);

    const res = await api.get(`/api/inventory/assets?surface=dependency`);
    expect(res.status()).toBe(200);
    const inventory = (await res.json()) as InventoryAssets;
    const mine = inventory.assets.filter((a) => a.location.startsWith(`project:${projectId}:`));

    // Every ecosystem is genuinely readable back, not merely accepted.
    const locations = mine.map((a) => a.location).sort();
    expect(locations).toContain(`project:${projectId}:pkg:maven/org.bouncycastle/bcprov-jdk18on`);
    expect(locations).toContain(`project:${projectId}:pkg:maven/net.i2p.crypto/eddsa`);
    expect(locations).toContain(`project:${projectId}:pkg:golang/github.com/btcsuite/btcd/btcec/v2`);
    expect(locations).toContain(`project:${projectId}:pkg:golang/github.com/cloudflare/circl`);
    expect(locations).toContain(`project:${projectId}:pkg:nuget/bouncycastle.cryptography`);
    expect(locations).toContain(`project:${projectId}:pkg:cargo/rsa`);

    // A library the curated table does not name produces nothing at all. It is
    // not "fine" — it is unexamined, and the absence of a row is how this
    // product says so rather than a green tick.
    expect(mine.every((a) => !a.location.includes("slf4j"))).toBe(true);
    expect(mine.every((a) => !a.location.includes("cobra"))).toBe(true);
    expect(mine.every((a) => !a.location.includes("serilog"))).toBe(true);
    expect(mine.every((a) => !a.location.includes("serde"))).toBe(true);

    const pick = (predicate: (a: InventoryAsset) => boolean, what: string): InventoryAsset => {
      const found = mine.find(predicate);
      expect(found, `${what} is missing from the inventory — locations present: ${locations.join(", ")}`).toBeDefined();
      return found!;
    };

    // A crate that exists to do one thing scores above a general-purpose
    // provider, and the difference survives to the inventory.
    const rsaCrate = pick((a) => a.location.endsWith("pkg:cargo/rsa"), "the rsa crate");
    expect(rsaCrate.algorithm).toBe("RSA");
    expect(Number(rsaCrate.latestConfidence)).toBeCloseTo(0.8, 5);
    const bouncyCastle = pick((a) => a.location.includes("bcprov-jdk18on"), "Bouncy Castle");
    expect(Number(bouncyCastle.latestConfidence)).toBeCloseTo(0.5, 5);

    // The one Go package that pins a single curve resolves to a key size; the
    // one that ships Ed25519 *and* Ed448 must not (G-05).
    expect(pick((a) => a.location.includes("btcec"), "btcec").keySize).toBe(256);
    expect(pick((a) => a.location.includes("circl") && a.algorithm === "EdDSA", "CIRCL's EdDSA asset").keySize).toBeNull();

    // An RSA library states no modulus size — the calling code picks it.
    expect(rsaCrate.keySize).toBeNull();
  });

  test("a Go-only resubmission never declares a Maven package gone", async ({ api }) => {
    const projectId = await createProject(api, "B2 per-ecosystem reconciliation");

    await submit(api, projectId, [
      { path: "gradle.lockfile", content: GRADLE_LOCKFILE },
      { path: "go.mod", content: GO_MOD },
    ]);

    // The Go tree shrinks; the Java tree was not looked at at all this time.
    const second = await submit(api, projectId, [
      { path: "go.mod", content: GO_MOD.replace("\tgithub.com/cloudflare/circl v1.3.9\n", "") },
    ]);

    expect(second.ecosystems).toEqual(["golang"]);
    // CIRCL contributed two assets (EdDSA and ECDH) and left the file. The
    // count is exact on purpose: "at least one" would pass just as happily if
    // the Maven assets had been swept up too, which is the bug this test is for.
    expect(second.assetsMarkedGone).toBe(2);

    const res = await api.get(`/api/inventory/assets?surface=dependency`);
    expect(res.status()).toBe(200);
    const mine = ((await res.json()) as InventoryAssets).assets.filter((a) =>
      a.location.startsWith(`project:${projectId}:`),
    );

    // The reconciliation scope is the point: a submission that carried no
    // Maven file has observed nothing about the Maven tree, so it may not
    // conclude a Maven package is gone. Present assets only come back here, so
    // Bouncy Castle still being listed is the assertion.
    expect(mine.some((a) => a.location.includes("bcprov-jdk18on"))).toBe(true);
    expect(mine.some((a) => a.location.includes("circl"))).toBe(false);
    expect(mine.some((a) => a.location.includes("btcec"))).toBe(true);
  });
});
